### ISSUE TITLE
Improve overall UX 

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/authit#42]
@marcopeereboom has given good feedbacks for this app, those are:

- Keep only the drag and drop, all the other stuff is making it needlessly complex
- For not-anchored results: show only a "not anchored yet" message, no buttons.
- For anchored results: show the all the results, but not the Merkle path
- For anchored results: verify the results agains't dcrdata

**Comment by vctt94** [comment]
I can remove the text input at https://github.com/decred/authit/pull/34.

I'll remove the commit aacbe415d7fe0892ec495e719db683349bd8c4f4 if you guys have no objections. This way I can avoid unnecessary changes at #34

**Comment by fernandoabolafio** [comment]
Sounds good to me. @tiagoalvesdulce need your opinion on this one.

**Comment by vctt94** [comment]
If we are going to remove https://github.com/decred/authit/commit/aacbe415d7fe0892ec495e719db683349bd8c4f4, someone with write access should remove it and force push. If it is done in a PR, it will generate conflicts. 

@tiagoalvesdulce what are your thoughts on this?

**Comment by vctt94** [comment]
I am working on this. 

I have two questions.
Right now we are not showing the merkle path for anchored results, do you guys mean when downloading the file?

![image](https://user-images.githubusercontent.com/15069783/52434666-1343a600-2af7-11e9-9cd4-ee384e8cf711.png)

And what does it mean to verify agains dcrdata? Because, right now, we are linking to dcrdata.

**Comment by fernandoabolafio** [comment]
I talked with @vctt94 and I will be working on this issue from now on.

**Comment by fernandoabolafio** [comment]
closed on #45
